import 'package:posventa/data/datasources/database_helper.dart';
import 'package:posventa/data/models/inventory_movement_model.dart';
import 'package:posventa/domain/entities/inventory_movement.dart';
import 'package:posventa/domain/repositories/inventory_movement_repository.dart';

class InventoryMovementRepositoryImpl implements InventoryMovementRepository {
  final DatabaseHelper _databaseHelper;

  InventoryMovementRepositoryImpl(this._databaseHelper);

  @override
  Future<void> createMovement(InventoryMovement movement) async {
    final model = InventoryMovementModel.fromEntity(movement);
    final map = model.toJson();
    map.remove('id'); // Ensure ID is generated by DB

    // Remove null values to avoid SQL issues
    map.removeWhere((key, value) => value == null);

    await _databaseHelper.insert(DatabaseHelper.tableInventoryMovements, map);
  }

  @override
  Future<void> deleteMovement(int id) async {
    await _databaseHelper.delete(DatabaseHelper.tableInventoryMovements, id);
  }

  @override
  Future<List<InventoryMovement>> getAllMovements() async {
    final db = await _databaseHelper.database;
    final result = await db.query(
      DatabaseHelper.tableInventoryMovements,
      orderBy: 'movement_date DESC',
    );
    return result.map((e) => InventoryMovementModel.fromJson(e)).toList();
  }

  @override
  Future<InventoryMovement?> getMovementById(int id) async {
    final result = await _databaseHelper.queryById(
      DatabaseHelper.tableInventoryMovements,
      id,
    );
    if (result != null) {
      return InventoryMovementModel.fromJson(result);
    }
    return null;
  }

  @override
  Future<List<InventoryMovement>> getMovementsByProduct(
    int productId, {
    int? variantId,
  }) async {
    final db = await _databaseHelper.database;
    final whereClause = variantId != null
        ? 'product_id = ? AND variant_id = ?'
        : 'product_id = ?';
    final whereArgs = variantId != null ? [productId, variantId] : [productId];

    final result = await db.query(
      DatabaseHelper.tableInventoryMovements,
      where: whereClause,
      whereArgs: whereArgs,
      orderBy: 'movement_date DESC',
    );
    return result.map((e) => InventoryMovementModel.fromJson(e)).toList();
  }

  @override
  Future<List<InventoryMovement>> getMovementsByWarehouse(
    int warehouseId,
  ) async {
    final db = await _databaseHelper.database;
    final result = await db.query(
      DatabaseHelper.tableInventoryMovements,
      where: 'warehouse_id = ?',
      whereArgs: [warehouseId],
      orderBy: 'movement_date DESC',
    );
    return result.map((e) => InventoryMovementModel.fromJson(e)).toList();
  }

  @override
  Future<List<InventoryMovement>> getMovementsByType(
    String movementType,
  ) async {
    final db = await _databaseHelper.database;
    final result = await db.query(
      DatabaseHelper.tableInventoryMovements,
      where: 'movement_type = ?',
      whereArgs: [movementType],
      orderBy: 'movement_date DESC',
    );
    return result.map((e) => InventoryMovementModel.fromJson(e)).toList();
  }

  @override
  Future<List<InventoryMovement>> getMovementsByDateRange(
    DateTime startDate,
    DateTime endDate,
  ) async {
    final db = await _databaseHelper.database;
    final result = await db.query(
      DatabaseHelper.tableInventoryMovements,
      where: 'movement_date BETWEEN ? AND ?',
      whereArgs: [startDate.toIso8601String(), endDate.toIso8601String()],
      orderBy: 'movement_date DESC',
    );
    return result.map((e) => InventoryMovementModel.fromJson(e)).toList();
  }

  @override
  Future<void> updateMovement(InventoryMovement movement) async {
    final model = InventoryMovementModel.fromEntity(movement);
    final map = model.toJson();

    // Remove null values except for id (needed for update)
    final id = map['id'];
    map.removeWhere((key, value) => value == null);
    map['id'] = id; // Restore id

    await _databaseHelper.update(DatabaseHelper.tableInventoryMovements, map);
  }
}
