import 'package:posventa/data/datasources/database_helper.dart';
import 'package:posventa/data/models/inventory_model.dart';
import 'package:posventa/domain/entities/inventory.dart';
import 'package:posventa/domain/repositories/inventory_repository.dart';

class InventoryRepositoryImpl implements InventoryRepository {
  final DatabaseHelper _databaseHelper;

  InventoryRepositoryImpl(this._databaseHelper);

  @override
  Future<void> createInventory(Inventory inventory) async {
    final model = InventoryModel.fromEntity(inventory);
    final map = model.toJson();
    map.remove('id'); // Ensure ID is generated by DB

    // Remove null values to avoid SQL issues
    map.removeWhere((key, value) => value == null);

    // Set initial updated_at
    map['updated_at'] = DateTime.now().toIso8601String();

    await _databaseHelper.insert(DatabaseHelper.tableInventory, map);
  }

  @override
  Future<void> deleteInventory(int id) async {
    await _databaseHelper.delete(DatabaseHelper.tableInventory, id);
  }

  @override
  Future<List<Inventory>> getAllInventory() async {
    final result = await _databaseHelper.queryAll(
      DatabaseHelper.tableInventory,
    );
    return result.map((e) => InventoryModel.fromJson(e)).toList();
  }

  @override
  Future<Inventory?> getInventoryById(int id) async {
    final result = await _databaseHelper.queryById(
      DatabaseHelper.tableInventory,
      id,
    );
    if (result != null) {
      return InventoryModel.fromJson(result);
    }
    return null;
  }

  @override
  Future<List<Inventory>> getInventoryByProduct(int productId) async {
    final db = await _databaseHelper.database;
    final result = await db.query(
      DatabaseHelper.tableInventory,
      where: 'product_id = ?',
      whereArgs: [productId],
    );
    return result.map((e) => InventoryModel.fromJson(e)).toList();
  }

  @override
  Future<List<Inventory>> getInventoryByWarehouse(int warehouseId) async {
    final db = await _databaseHelper.database;
    final result = await db.query(
      DatabaseHelper.tableInventory,
      where: 'warehouse_id = ?',
      whereArgs: [warehouseId],
    );
    return result.map((e) => InventoryModel.fromJson(e)).toList();
  }

  @override
  Future<void> updateInventory(Inventory inventory) async {
    final model = InventoryModel.fromEntity(inventory);
    final map = model.toJson();

    // Remove null values except for id (needed for update)
    final id = map['id'];
    map.removeWhere((key, value) => value == null);
    map['id'] = id; // Restore id

    // Update timestamp
    map['updated_at'] = DateTime.now().toIso8601String();

    await _databaseHelper.update(DatabaseHelper.tableInventory, map);
  }
}
