import 'package:posventa/domain/entities/inventory_movement.dart';
import 'package:posventa/domain/entities/product.dart';
import 'package:posventa/domain/entities/warehouse.dart';
import 'package:posventa/presentation/providers/providers.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';

part 'inventory_adjustment_provider.g.dart';

class AdjustmentItem {
  final Product product;
  final Warehouse warehouse;
  final double quantity; // The adjustment amount (e.g., +5, -2)
  final double currentStock;
  final String reason;
  final MovementType type;

  AdjustmentItem({
    required this.product,
    required this.warehouse,
    required this.quantity,
    required this.currentStock,
    required this.reason,
    required this.type,
  });

  AdjustmentItem copyWith({
    Product? product,
    Warehouse? warehouse,
    double? quantity,
    double? currentStock,
    String? reason,
    MovementType? type,
  }) {
    return AdjustmentItem(
      product: product ?? this.product,
      warehouse: warehouse ?? this.warehouse,
      quantity: quantity ?? this.quantity,
      currentStock: currentStock ?? this.currentStock,
      reason: reason ?? this.reason,
      type: type ?? this.type,
    );
  }
}

@riverpod
class InventoryAdjustmentNotifier extends _$InventoryAdjustmentNotifier {
  @override
  List<AdjustmentItem> build() {
    return [];
  }

  void addItem(AdjustmentItem item) {
    state = [...state, item];
  }

  void removeItem(int index) {
    state = [...state]..removeAt(index);
  }

  void updateItem(int index, AdjustmentItem item) {
    final newState = [...state];
    newState[index] = item;
    state = newState;
  }

  void clear() {
    state = [];
  }

  Future<void> submitAdjustments(int userId) async {
    if (state.isEmpty) return;

    final movements = state.map((item) {
      return InventoryMovement(
        id: 0, // Generated by DB
        productId: item.product.id!,
        warehouseId: item.warehouse.id!,
        movementType: item.type,
        quantity: item.quantity,
        quantityBefore: item.currentStock,
        quantityAfter: item.currentStock + item.quantity,
        referenceType: 'adjustment',
        referenceId: 0, // No specific reference ID for manual adjustment
        reason: item.reason,
        performedBy: userId,
        movementDate: DateTime.now(),
      );
    }).toList();

    await ref.read(adjustInventoryBatchUseCaseProvider).call(movements);
    clear();
  }
}
