import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:posventa/domain/entities/inventory_audit.dart';
import 'package:posventa/presentation/providers/inventory/inventory_audit_view_model.dart';

class QuickAuditView extends ConsumerStatefulWidget {
  final InventoryAuditEntity audit;

  const QuickAuditView({super.key, required this.audit});

  @override
  ConsumerState<QuickAuditView> createState() => _QuickAuditViewState();
}

class _QuickAuditViewState extends ConsumerState<QuickAuditView> {
  @override
  Widget build(BuildContext context) {
    final theme = Theme.of(context);

    // Watch the index from our new QuickAuditState provider
    // Note: We access the provider generated by Riverpod Generator.
    // Ensure 'quickAuditStateProvider' is available after build_runner.
    final currentIndex = ref.watch(quickAuditStateProvider);

    if (currentIndex < 0 || currentIndex >= widget.audit.items.length) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(
              Icons.check_circle_outline,
              size: 64,
              color: Colors.green,
            ),
            const SizedBox(height: 16),
            Text(
              'Has llegado al final de la lista.',
              style: theme.textTheme.headlineSmall,
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 24),
            FilledButton(
              onPressed: () {
                // Exit Quick Mode
                ref
                    .read(inventoryAuditViewModelProvider.notifier)
                    .exitQuickAudit();
              },
              child: const Text('Volver a la Lista'),
            ),
          ],
        ),
      );
    }

    final item = widget.audit.items[currentIndex];
    final totalItems = widget.audit.items.length;
    final progress = (currentIndex + 1) / totalItems;

    return Scaffold(
      appBar: AppBar(
        title: Text('Modo Rápido: ${currentIndex + 1} / $totalItems'),
        leading: IconButton(
          icon: const Icon(Icons.close),
          onPressed: () {
            ref.read(inventoryAuditViewModelProvider.notifier).exitQuickAudit();
          },
        ),
        bottom: PreferredSize(
          preferredSize: const Size.fromHeight(4),
          child: LinearProgressIndicator(value: progress),
        ),
      ),
      body: Padding(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.stretch,
          children: [
            // Product Card
            Expanded(
              child: Card(
                elevation: 4,
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(16),
                ),
                child: Padding(
                  padding: const EdgeInsets.all(24.0),
                  child: Column(
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: [
                      // Product Icon/Image
                      Container(
                        padding: const EdgeInsets.all(24),
                        decoration: BoxDecoration(
                          color: theme.colorScheme.surfaceContainerHighest
                              .withValues(alpha: 0.3),
                          shape: BoxShape.circle,
                        ),
                        child: Icon(
                          Icons.inventory_2,
                          size: 64,
                          color: theme.colorScheme.primary,
                        ),
                      ),
                      const SizedBox(height: 24),

                      // Product Name & Variant
                      Text(
                        item.productName ?? 'Producto Desconocido',
                        style: theme.textTheme.headlineMedium?.copyWith(
                          fontWeight: FontWeight.bold,
                        ),
                        textAlign: TextAlign.center,
                      ),
                      if (item.variantName != null) ...[
                        const SizedBox(height: 8),
                        Text(
                          item.variantName!,
                          style: theme.textTheme.titleLarge?.copyWith(
                            color: theme.colorScheme.secondary,
                          ),
                          textAlign: TextAlign.center,
                        ),
                      ],
                      const SizedBox(height: 16),
                      Container(
                        padding: const EdgeInsets.symmetric(
                          horizontal: 12,
                          vertical: 6,
                        ),
                        decoration: BoxDecoration(
                          color: theme.colorScheme.surfaceContainerHighest,
                          borderRadius: BorderRadius.circular(8),
                        ),
                        child: Text(
                          'Código: ${item.barcode ?? 'N/A'}',
                          style: theme.textTheme.bodyLarge?.copyWith(
                            fontFamily: 'Monospace',
                          ),
                        ),
                      ),

                      const Spacer(),

                      // Counts Comparison
                      Row(
                        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                        children: [
                          _buildCountInfo(
                            context,
                            'Sistema',
                            '${item.expectedQuantity}',
                          ),
                          const Icon(Icons.arrow_forward, color: Colors.grey),
                          // Default to system count for rapid confirmation view
                          _buildCountInfo(
                            context,
                            'Físico Sugerido',
                            '${item.expectedQuantity}', // Showing expected as default
                            isHighlight: true,
                          ),
                        ],
                      ),
                      const Spacer(),
                    ],
                  ),
                ),
              ),
            ),
            const SizedBox(height: 24),

            // Actions
            SizedBox(
              height: 56,
              child: Row(
                children: [
                  Expanded(
                    flex: 1,
                    child: OutlinedButton(
                      style: OutlinedButton.styleFrom(
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        side: BorderSide(color: theme.colorScheme.error),
                        padding: EdgeInsets.zero,
                        foregroundColor: theme.colorScheme.error,
                      ),
                      onPressed: () => _showEditDialog(context, item),
                      child: const Column(
                        mainAxisAlignment: MainAxisAlignment.center,
                        children: [
                          Text(
                            'Editar',
                            style: TextStyle(fontWeight: FontWeight.bold),
                          ),
                          Text('Diferencia', style: TextStyle(fontSize: 10)),
                        ],
                      ),
                    ),
                  ),
                  const SizedBox(width: 12),
                  Expanded(
                    flex: 2,
                    child: FilledButton.icon(
                      style: FilledButton.styleFrom(
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(16),
                        ),
                        backgroundColor: const Color(
                          0xFF4CAF50,
                        ), // Google Green
                        foregroundColor: Colors.white,
                        elevation: 2,
                      ),
                      onPressed: () {
                        ref
                            .read(inventoryAuditViewModelProvider.notifier)
                            .confirmQuickAuditItemAndNext(
                              item.expectedQuantity,
                            );
                      },
                      icon: const Icon(Icons.check_circle_outline),
                      label: const Text(
                        'Confirmar',
                        style: TextStyle(
                          fontSize: 18,
                          fontWeight: FontWeight.bold,
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
            const SizedBox(height: 12),
            // Navigation without saving (Skip?)
            // Navigation
            Padding(
              padding: const EdgeInsets.only(bottom: 24.0),
              child: Row(
                children: [
                  Expanded(
                    child: OutlinedButton.icon(
                      style: OutlinedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        side: BorderSide(
                          color: theme.colorScheme.outlineVariant,
                        ),
                        shape: const StadiumBorder(),
                        foregroundColor: theme.colorScheme.onSurface,
                      ),
                      onPressed: () {
                        ref.read(quickAuditStateProvider.notifier).previous();
                      },
                      icon: const Icon(Icons.arrow_back, size: 20),
                      label: const Text('Anterior'),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: FilledButton.icon(
                      style: FilledButton.styleFrom(
                        backgroundColor: Theme.of(
                          context,
                        ).colorScheme.secondaryContainer,
                        foregroundColor: Theme.of(
                          context,
                        ).colorScheme.onSecondaryContainer,
                        padding: const EdgeInsets.symmetric(vertical: 16),
                        shape: const StadiumBorder(),
                        elevation: 0,
                      ),
                      onPressed: () {
                        ref.read(quickAuditStateProvider.notifier).next();
                      },
                      icon: const Icon(Icons.arrow_forward, size: 20),
                      label: const Text('Siguiente'),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }

  Widget _buildCountInfo(
    BuildContext context,
    String label,
    String value, {
    bool isHighlight = false,
  }) {
    final theme = Theme.of(context);
    return Column(
      children: [
        Text(label, style: theme.textTheme.bodySmall),
        const SizedBox(height: 4),
        Text(
          value,
          style: theme.textTheme.displaySmall?.copyWith(
            fontWeight: FontWeight.bold,
            color: isHighlight ? Colors.green : null,
          ),
        ),
      ],
    );
  }

  void _showEditDialog(BuildContext context, InventoryAuditItemEntity item) {
    final controller = TextEditingController(text: '${item.expectedQuantity}');
    showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Ingresar Cantidad Física Real'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
              controller: controller,
              keyboardType: const TextInputType.numberWithOptions(
                decimal: true,
              ),
              autofocus: true,
              decoration: const InputDecoration(
                labelText: 'Cantidad',
                border: OutlineInputBorder(),
                suffixText: 'Unidades',
              ),
            ),
          ],
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.pop(context),
            child: const Text('Cancelar'),
          ),
          FilledButton(
            onPressed: () {
              final val = double.tryParse(controller.text) ?? 0.0;
              Navigator.pop(context);
              // Save and Next
              ref
                  .read(inventoryAuditViewModelProvider.notifier)
                  .confirmQuickAuditItemAndNext(val);
            },
            child: const Text('Guardar y Siguiente'),
          ),
        ],
      ),
    );
  }
}
